portal/portal-web/src/main/java/br/com/mar/ttg/portal/service/util/BaseController.java
package br.com.mar.ttg.portal.service.util;
import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.primefaces.component.datatable.DataTable;
import org.primefaces.context.RequestContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

/**
 * 
 * @author ggraf
 *
 */
public class BaseController implements Serializable {

	private static final long serialVersionUID = -6314656601181178598L;

	private static final Logger LOGGER = LoggerFactory.getLogger(BaseController.class);

	//	Dialog Messages
	protected void returnInfoDialogMessage(String title, String message) {
		if (StringUtils.isEmpty(title)) {
			title = "AVISO";
		}

		returnDialogMessage(title, message, FacesMessage.SEVERITY_INFO);
	}

	protected void returnWarnDialogMessage(String title, String message, Throwable t) {
		if (StringUtils.isEmpty(title)) {
			title = "AVISO";
		}

		if (null != t) {
			LOGGER.warn(title, t);
		}

		returnDialogMessage(title, message, FacesMessage.SEVERITY_WARN);

	}

	protected void returnErrorDialogMessage(String title, String message, Throwable t) {
		if (StringUtils.isEmpty(title)) {
			title = "ERRO";
		}

		if (null != t) {
			LOGGER.error(title, t);
		}

		returnDialogMessage(title, message, FacesMessage.SEVERITY_ERROR);

	}

	protected void returnFatalDialogMessage(String title, String message, Throwable t) {
		if (StringUtils.isEmpty(title)) {
			title = "ERRO FATAL";
		}

		if (null != t) {
			LOGGER.error(title, t);
		}

		returnDialogMessage(title, message, FacesMessage.SEVERITY_FATAL);
	}

	private void returnDialogMessage(String title, String message, Severity severity) {
		RequestContext.getCurrentInstance().showMessageInDialog(new FacesMessage(severity, title, message));
	}

	//	Messages
	protected void returnInfoMessage(String message, String target) {
		returnMessage(message, FacesMessage.SEVERITY_INFO, target);
	}

	protected void returnWarnMessage(String message, String target, Throwable t) {
		if (null != t) {
			LOGGER.warn("Aviso", t);
		}
		returnMessage(message, FacesMessage.SEVERITY_WARN, target);

	}

	protected void returnErrorMessage(String message, String target, Throwable t) {
		if (null != t) {
			LOGGER.error("Erro", t);
		}
		returnMessage(message, FacesMessage.SEVERITY_ERROR, target);

	}

	protected void returnFatalMessage(String message, String target, Throwable t) {
		if (null != t) {
			LOGGER.error("Erro fatal", t);
		}
		returnMessage(message, FacesMessage.SEVERITY_FATAL, target);
	}

	private void returnMessage(String message, Severity severity, String target) {
		FacesContext context = FacesContext.getCurrentInstance();
		if (StringUtils.isNotEmpty(target)) {
			redirectView(target, context);
		}
		context.addMessage("message", new FacesMessage(severity, message, ""));
	}

	//	Dialogs
	protected void showDialog(String name) {
		RequestContext rc = RequestContext.getCurrentInstance();
		rc.execute("PF('" + name + "').show()");
	}

	protected void hideDialog(String name) {
		RequestContext rc = RequestContext.getCurrentInstance();
		rc.execute("PF('" + name + "').hide()");
	}

	//	Components
	protected void updateComponent(String id) {
		RequestContext rc = RequestContext.getCurrentInstance();
		rc.update(id);
	}

	protected void resetTable(String id) {
		DataTable dataTable = (DataTable) FacesContext.getCurrentInstance().getViewRoot().findComponent(id);
		if (null != dataTable) {
			dataTable.setSortBy(null);
			if (dataTable.isPaginator()) {
				dataTable.setPaginatorPosition("0");
			}
		}
	}

	// Utilities
	protected void redirectView(String target) {
		redirectView(target, null);
	}

	protected void redirectView(String target, FacesContext context) {
		if (null == context) {
			context = FacesContext.getCurrentInstance();
		}

		try {
			context.getExternalContext().getFlash().setKeepMessages(true);
			context.getExternalContext().getFlash().setRedirect(true);
			context.getExternalContext().redirect(target);
		} catch (Throwable t) {
			LOGGER.error("Error redirecting page", t);
		}
	}

	protected String getApplicationUrl() {
		HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		String url = request.getRequestURL().toString().replace(request.getRequestURI(), "") + request.getContextPath();

		return url;
	}

	public String getActualView() {
		FacesContext context = FacesContext.getCurrentInstance();
		if (null == context || null == context.getViewRoot()) {
			return "";
		}
		return context.getViewRoot().getViewId();
	}



	public HttpSession getSession(boolean createSession) {
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(createSession);

		return session;
	}

	public Object getSessionAttribute(String name, boolean createSession) {
		return getSession(createSession).getAttribute(name);
	}

	public void setSessionAttribute(String name, Object value, boolean createSession) {
		getSession(createSession).setAttribute(name, value);
	}

	public String getClientIp() {
		HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		return request.getRemoteAddr();
	}

	public String getSessionId() {
		return ((HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false)).getId();
	}

	public boolean isView(String name) {
		return getActualView().contains(name);
	}

	public UsernamePasswordAuthenticationToken getAuthenticatedUser() {
		UsernamePasswordAuthenticationToken user = (UsernamePasswordAuthenticationToken) SecurityContextHolder.getContext().getAuthentication();

		return user;
	}
}

portal/portal-web/src/main/java/br/com/mar/ttg/portal/web/controller/SessionController.java
package br.com.mar.ttg.portal.web.controller;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Scope;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;

import br.com.mar.ttg.portal.service.util.BaseController;
import br.com.mar.ttg.portal.web.util.I18NUtil;
import br.com.mar.ttg.portal.web.util.SessionUtil;

/**
 * 
 * @author ggraf
 *
 */
@Controller
@Scope("session")
public class SessionController extends BaseController implements InitializingBean {

	private static final long serialVersionUID = 8303028606794937818L;

	@Value("${version}")
	private String versaoSistema;

	@Value("${build.date}")
	private String dataBuild;

	@Override
	public void afterPropertiesSet() throws Exception {
		try {
		} catch (Throwable t) {
			returnFatalDialogMessage(I18NUtil.getMessage("erro"), I18NUtil.getMessage("erro_sessao"), t);
		}
	}

	public boolean isAuthenticated() {
		if (null == SecurityContextHolder.getContext().getAuthentication()
				|| SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken) {
			return false;
		}
		return true;
	}

	public static boolean possuiPermissao(String permissao) {
		return SessionUtil.possuiPermissao(permissao);
	}

	// Getters e Setters
	public String getVersaoSistema() {
		return versaoSistema;
	}

	public String getDataBuild() {
		return dataBuild;
	}
}

portal/portal-web/src/main/webapp/pages/common/footer.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">

	<div id="footer">
		
	</div>

</ui:fragment>

portal/portal-web/src/main/webapp/pages/common/head.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">

	<h:head>
		<title>#{labels.sistema_titulo}</title>
		<f:facet name="first">
			<meta http-equiv="X-UA-Compatible" content="IE=9,chrome=1" />
			<meta content="text/html; charset=UTF-8" http-equiv="content-type" />
			<meta name="viewport" content="width=device-width, user-scalable=no" />
		</f:facet>

		<h:outputScript name="js/locale.js" />
		<h:outputScript name="js/mask.js" />
		<h:outputScript name="js/common.js" />
		<h:outputScript name="js/close.js" />
		<h:outputScript name="js/cookie.js" />

		<link rel="stylesheet" type="text/css" href="#{request.contextPath}/css/app.css" />
		<link rel="stylesheet" type="text/css" href="#{request.contextPath}/css/fonts.css" />

	</h:head>

</ui:fragment>

portal/portal-web/src/main/webapp/pages/common/header.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">

	<div id="header">
		<a href="#{request.contextPath}">
			<div id="logo_cabecalho">
				<p:graphicImage value="#{resource['primefaces-ttg:images/dorime.png']}" />
			</div>
		</a>

		<div style="float: right; height: 100%; line-height: 70px;">
			<h:outputText value="#{sessionController.versaoSistema} - #{sessionController.dataBuild}" style="margin-right: 10px;" />
		</div>
	</div>

	<form id="logoutForm" action="#{request.contextPath}/j_spring_security_logout" method="post"></form>

	<ui:insert name="menu">
		<ui:include src="/pages/common/menu.xhtml" />
	</ui:insert>

	<p:idleMonitor timeout="1800000">
		<p:ajax event="idle" onstart="atualizaPagina(); " />
	</p:idleMonitor>
</ui:fragment>

portal/portal-web/src/main/webapp/pages/common/loading.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">

	<p:ajaxStatus onstart="PF('statusDialog').show();" onsuccess="PF('statusDialog').hide();" onerror="PF('statusDialog').hide();">
		<p:dialog modal="true" widgetVar="statusDialog" resizable="false" draggable="false" closable="false" showHeader="false"
			style="background: transparent !important; border: 0 !important;">
			<div style="text-align: center;">
				<span style="color: #fff; font-size: 25px;">#{messages.carregando}</span> <br />
				<p:graphicImage value="#{resource['primefaces-ttg:images/loading.gif']}" />
			</div>
		</p:dialog>
	</p:ajaxStatus>

	<script type="text/javascript">
		function showStatus() {
			PF('statusDialog').show();
		}

		function hideStatus() {
			PF('statusDialog').hide();
		}
	</script>

</ui:fragment>

portal/portal-web/src/main/webapp/pages/common/menu.xhtml
<ui:fragment xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core" xmlns:shiro="http://shiro.apache.org/tags"
	xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:sec="http://www.springframework.org/security/tags">

	<p:spacer rendered="#{!sessionController.authenticated}" style="width: 48px" />
	<h:panelGrid columns="2" width="100%" styleClass="gridMenu" columnClasses=",alignRight" rendered="#{sessionController.authenticated}">
		<h:form prependId="false" id="formMenu">
			<f:event type="preRenderView" listener="#{permissaoMenuFilter.filtraMenuVazio}" />
			<p:menubar id="menu" autoDisplay="false">
				<p:menuitem icon="fa fa-fw fa-home" value="#{labels.menu_inicio}" url="/pages/home.jsf" />

				<p:submenu icon="fa fa-fw fa-gears" label="#{labels.menu_administracao}">

					<p:submenu icon="fa fa-fw fa-unlock" label="#{labels.menu_administracao_acesso}">
						<p:submenu icon="fa fa-fw fa-user" label="#{labels.menu_administracao_acesso_usuario}">
							<p:menuitem icon="fa fa-fw fa-suitcase" value="#{labels.menu_administracao_acesso_usuario_colaborador}"
								url="/pages/administracao/acesso/usuario/colaborador.jsf"
								rendered="#{sec:isAllowed('/pages/administracao/acesso/usuario/colaborador.jsf', '')}" />
							<p:menuitem icon="fa fa-fw fa-magic" value="#{labels.menu_administracao_acesso_usuario_sistema}"
								url="/pages/administracao/acesso/usuario/sistema.jsf" rendered="#{sec:isAllowed('/pages/administracao/acesso/usuario/sistema.jsf', '')}" />
							<p:menuitem icon="fa fa-fw fa-bell" value="#{labels.menu_administracao_acesso_usuario_externo}"
								url="/pages/administracao/acesso/usuario/externo.jsf" rendered="#{sec:isAllowed('/pages/administracao/acesso/usuario/usuario.jsf', '')}" />
						</p:submenu>
						<p:menuitem icon="fa fa-fw fa-star" value="#{labels.menu_administracao_acesso_perfil}" url="/pages/administracao/acesso/perfil.jsf"
							rendered="#{sec:isAllowed('/pages/administracao/acesso/perfil.jsf', '')}" />
					</p:submenu>

					<p:submenu icon="fa fa-fw fa-folder-open" label="#{labels.menu_administracao_auxiliar}">
						<p:menuitem icon="fa fa-fw fa-folder" value="#{labels.menu_administracao_auxiliar_departamento}"
							url="/pages/administracao/auxiliar/departamento.jsf" rendered="#{sec:isAllowed('/pages/administracao/auxiliar/departamento.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-list-ol" value="#{labels.menu_administracao_auxiliar_nivel_hierarquia}"
							url="/pages/administracao/auxiliar/nivel_hierarquia.jsf" rendered="#{sec:isAllowed('/pages/administracao/auxiliar/nivel_hierarquia.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-bank" value="#{labels.menu_administracao_auxiliar_banco}" url="/pages/administracao/auxiliar/banco.jsf"
							rendered="#{sec:isAllowed('/pages/administracao/auxiliar/banco.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-sitemap" value="#{labels.menu_administracao_auxiliar_codigo_contabil}"
							url="/pages/administracao/auxiliar/codigo_contabil.jsf" rendered="#{sec:isAllowed('/pages/administracao/auxiliar/codigo_contabil.jsf', '')}" />
					</p:submenu>

					<p:submenu icon="fa fa-fw fa-bar-chart" label="#{labels.menu_administracao_avaliacao}">
						<p:menuitem icon="fa fa-fw fa-bullseye" value="#{labels.menu_administracao_avaliacao_processo}"
							url="/pages/administracao/avaliacao/processo.jsf" rendered="#{sec:isAllowed('/pages/administracao/avaliacao/processo.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-paperclip" value="#{labels.menu_administracao_avaliacao_escala}" url="/pages/administracao/avaliacao/escala.jsf"
							rendered="#{sec:isAllowed('/pages/administracao/avaliacao/escala.jsf', '')}" />
					</p:submenu>

					<p:submenu icon="fa fa-fw fa-inbox" label="#{labels.menu_administracao_cadastro}">
						<p:submenu icon="fa fa-fw fa-institution" label="#{labels.menu_administracao_cadastro_parceiro}">
							<p:menuitem icon="fa fa-fw fa-building" value="#{labels.menu_administracao_cadastro_parceiro_cliente_fornecedor}"
								url="/pages/administracao/cadastro/parceiro/cliente_fornecedor.jsf"
								rendered="#{sec:isAllowed('/pages/administracao/cadastro/parceiro/cliente_fornecedor.jsf', '')}" />
							<p:menuitem icon="fa fa-fw fa-bank" value="#{labels.menu_administracao_cadastro_parceiro_fundo}"
								url="/pages/administracao/cadastro/parceiro/fundo.jsf" rendered="#{sec:isAllowed('/pages/administracao/cadastro/parceiro/fundo.jsf', '')}" />
						</p:submenu>
					</p:submenu>

					<p:submenu icon="fa fa-fw fa-file" label="#{labels.menu_administracao_contratos}">
						<p:menuitem icon="fa fa-fw fa-paperclip" value="#{labels.menu_administracao_contratos_tipo}" url="/pages/administracao/contratos/tipo.jsf"
							rendered="#{sec:isAllowed('/pages/administracao/contratos/tipo.jsf', '')}" />
					</p:submenu>
				</p:submenu>

				<p:submenu icon="fa fa-fw fa-file" label="#{labels.menu_contratos}">
					<p:menuitem icon="fa fa-fw fa-file-text" value="#{labels.menu_contratos_requisicao}" url="/pages/contratos/requisicao.jsf"
						rendered="#{sec:isAllowed('/pages/contratos/requisicao.jsf', '')}" />
						
						<p:menuitem icon="fa fa-fw fa-file-text-o" value="#{labels.menu_contratos_vendas_madeira}" url="/pages/contratos/contrato_vendas_madeira.jsf" 
						rendered="#{sec:isAllowed('/pages/contratos/contrato_vendas_madeira.jsf', '')}" />
						
					<p:menuitem icon="fa fa-fw fa-table" value="#{labels.menu_contratos_requisicao_consulta}" url="/pages/contratos/requisicao_consulta.jsf"
						rendered="#{sec:isAllowed('/pages/contratos/requisicao_consulta.jsf', '')}" />
					<p:menuitem icon="fa fa-fw fa-search" value="#{labels.menu_contratos_contrato_consulta}" url="/pages/contratos/contrato_consulta.jsf"
						rendered="#{sec:isAllowed('/pages/contratos/contrato_consulta.jsf', '')}" />
					<p:menuitem icon="fa fa-fw fa-history" value="#{labels.menu_contratos_historico}" url="/pages/contratos/historico.jsf"
						rendered="#{sec:isAllowed('/pages/contratos/historico.jsf', '')}" />
				</p:submenu>

				<p:submenu icon="fa fa-fw fa-users" label="#{labels.menu_pessoas}">
					<p:submenu icon="fa fa-fw fa-bar-chart" label="#{labels.menu_pessoas_avaliacao}">
						<p:menuitem icon="fa fa-fw fa-search" value="#{labels.menu_pessoas_avaliacao_consulta}" url="/pages/pessoas/avaliacao/consulta.jsf"
							rendered="#{sec:isAllowed('/pages/pessoas/avaliacao/consulta.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-forward" value="#{labels.menu_pessoas_avaliacao_indicacao}" url="/pages/pessoas/avaliacao/indicacao.jsf"
							rendered="#{sec:isAllowed('/pages/pessoas/avaliacao/indicacao.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-pencil" value="#{labels.menu_pessoas_avaliacao_processo}" url="/pages/pessoas/avaliacao/processo.jsf"
							rendered="#{sec:isAllowed('/pages/pessoas/avaliacao/processo.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-check" value="#{labels.menu_pessoas_avaliacao_resultado}" url="/pages/pessoas/avaliacao/resultado.jsf"
							rendered="#{sec:isAllowed('/pages/pessoas/avaliacao/resultado.jsf', '')}" />
						<p:menuitem icon="fa fa-fw fa-line-chart" value="#{labels.menu_pessoas_avaliacao_dashboard}" url="/pages/pessoas/avaliacao/dashboard.jsf"
							rendered="#{sec:isAllowed('/pages/pessoas/avaliacao/dashboard.jsf', '')}" />
					</p:submenu>
				</p:submenu>
				
					<p:menuitem icon="fa fa-fw fa-file" value="#{labels.menu_relatorio_etapas}" url="/pages/contratos/relatorio_etapas.jsf"
						rendered="#{sec:isAllowed('/pages/contratos/relatorio_etapas.jsf', '')}" />
			</p:menubar>
		</h:form>

		<h:form rendered="#{sessionController.authenticated}">
			<h:panelGrid columns="2" style="float: right !important; width: min-width: 300px !important;">
				<p:link href="/pages/pessoas/contatos.jsf" style="margin-right: 30px; font-size: 25px; color: #00457C !important;"
					rendered="#{sec:isAllowed('/pages/pessoas/contatos.jsf', '')}" title="#{labels.menu_pessoas_contatos}">
					<h:outputText class="fa fa-fw fa-address-book" />
				</p:link>
				<p:commandButton id="menuUsuario" value="#{sessionController.authenticatedUser.principal.usuario.nome}" type="button" icon="fa fa-fw fa-user"
					style="margin-right: 20px; min-width: 150px; border: #F6F6F6 1px solid !important;" />
				<p:menu overlay="true" trigger="menuUsuario" my="left top" at="left bottom">
					<p:menuitem icon="fa fa-fw fa-key" value="#{labels.menu_usuario_acesso_alteracao_senha}" url="/pages/usuario/acesso/alteracao_senha.jsf" />
					<p:menuitem icon="fa fa-fw fa-sign-out" value="#{labels.menu_sair}" onclick="PF('statusDialog').show();"
						url="javascript:document.getElementById('logoutForm').submit();" />
				</p:menu>
			</h:panelGrid>
		</h:form>
	</h:panelGrid>
</ui:fragment>