portal-web/src/main/java/br/com/mar/ttg/portal/data/entity/acesso/Usuario.java
package br.com.mar.ttg.portal.data.entity.acesso;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import antlr.StringUtils;
import br.com.mar.ttg.portal.dom.DomAcesso;
import br.com.mar.ttg.portal.dom.DomAcesso.DomStatusUsuario;

/**
 * 
 * @author ggraf
 *
 */
@Entity
@Table(name = "tb_usuario")
@Inheritance(strategy = InheritanceType.JOINED)
public class Usuario implements Serializable {

	private static final long serialVersionUID = -2292295356317092628L;

	public static final String TIPO_SISTEMA = "S";
	public static final String TIPO_COLABORADOR = "C";
	public static final String TIPO_EXTERNO = "E";

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_USUARIO")
	@SequenceGenerator(name = "SQ_USUARIO", sequenceName = "SQ_USUARIO", allocationSize = 1)
	@Column(name = "id", nullable = false)
	private Integer id;

	@Column(name = "email", nullable = false)
	private String email;

	@Column(name = "nome", nullable = false)
	private String nome;

	@Column(name = "senha", nullable = false)
	private String senha;

	@Column(name = "id_perfil", nullable = false)
	private Integer idPerfil;

	@Column(name = "tipo", nullable = false)
	private String tipo;

	@Column(name = "telefone")
	private String telefone;

	@Column(name = "ramal")
	private String ramal;

	@Column(name = "celular")
	private String celular;

	@Column(name = "status", nullable = false)
	private String status;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public Integer getIdPerfil() {
		return idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getRamal() {
		return ramal;
	}

	public void setRamal(String ramal) {
		this.ramal = ramal;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean isAtivo() {
		return null != status && DomStatusUsuario.ATIVO.equals(status);
	}

	public String getDeStatus() {
		return DomAcesso.domStatusUsuario.getDeValor(status);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}

portal-web/src/main/webapp/pages/administracao/contratos/tipo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<ui:composition template="/pages/templates/crud_template.xhtml">

	<ui:define name="breadCrumb">
		<h2>#{labels.menu_administracao} / #{labels.menu_administracao_contratos} / #{labels.menu_administracao_contratos_tipo}</h2>
	</ui:define>

	<ui:define name="searchGrid">
		<h:panelGrid id="searchGrid" width="100%" rendered="#{null == tipoContratoController.entity}">

			<h:panelGrid columns="4" width="100%" columnClasses=",,,alignRight" id="filterGrid">
				<p:outputLabel for="nomeFilter" value="#{labels.nome}" styleClass="label" />
				<p:outputLabel for="modeloFilter" value="#{labels.modelo}" styleClass="label" />
				<p:outputLabel for="statusFilter" value="#{labels.status}" styleClass="label" />
				<p:spacer />

				<p:inputText id="nomeFilter" style="width: 350px;" value="#{tipoContratoController.filterEntity.nome}" maxlength="50" />
				<p:selectOneMenu id="modeloFilter" value="#{tipoContratoController.filterEntity.modelo}" style="width:200px;">
					<f:selectItem itemLabel="" itemValue="" />
					<f:selectItems value="#{domContratosController.modeloRequisicaoMap}" />
				</p:selectOneMenu>
				<p:selectOneMenu id="statusFilter" value="#{tipoContratoController.filterEntity.status}" style="width:100px;">
					<f:selectItem itemLabel="" itemValue="" />
					<f:selectItems value="#{domContratosController.statusTipoMap}" />
				</p:selectOneMenu>
				<p:commandButton value="#{labels.botao_pesquisar}" id="searchButton" icon="fa fa-fw fa-search" update="dtbEntities searchMessages"
					actionListener="#{tipoContratoController.search}" process="@this, filterGrid" oncomplete="PF('dtb').getPaginator().setPage(0);" />
			</h:panelGrid>

			<p:spacer height="10px" />
			<p:separator />
			<p:spacer height="10px" />
			<p:messages id="searchMessages" />

			<p:dataTable widgetVar="dtb" id="dtbEntities" var="entity" emptyMessage="#{labels.nenhum_resultado}" value="#{tipoContratoController.entities}"
				paginator="true" paginatorPosition="bottom" rows="15" currentPageReportTemplate="{currentPage} #{labels.de} {totalPages}"
				paginatorAlwaysVisible="false"
				paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}">

				<p:column headerText="#{labels.nome}" sortBy="#{entity.nome}" style="text-align: center;">
					<h:outputText value="#{entity.nome}" />
				</p:column>

				<p:column headerText="#{labels.modelo}" sortBy="#{entity.deModelo}" style="text-align: center; width: 150px;">
					<h:outputText value="#{entity.deModelo}" />
				</p:column>

				<p:column headerText="#{labels.aprovacao_presidencia}" sortBy="#{entity.deAprovacaoPresidencia}" style="text-align: center; width: 200px;">
					<h:outputText value="#{entity.deAprovacaoPresidencia}" />
				</p:column>

				<p:column headerText="#{labels.versao}" sortBy="#{entity.versao}" style="text-align: center; width: 90px;">
					<h:outputText value="#{entity.versao}" />
				</p:column>

				<p:column headerText="#{labels.status}" sortBy="#{entity.deStatus}" style="text-align: center; width: 100px;">
					<h:outputText value="#{entity.deStatus}" />
				</p:column>

				<p:column style="width:40px; text-align: center;">
					<f:facet name="header">#{labels.acoes}</f:facet>
					<p:commandButton icon="fa fa-fw fa-pencil" title="#{labels.botao_editar}" update=":searchForm :editForm" process="@this" resetValues="true">
						<f:setPropertyActionListener value="#{entity}" target="#{tipoContratoController.selectedEntity}" />
					</p:commandButton>
				</p:column>

				<f:facet name="header">
					<p:commandButton value="#{labels.botao_adicionar} " icon="fa fa-fw fa-plus" actionListener="#{tipoContratoController.add}"
						update=":searchForm :editForm" process="@this" resetValues="true" />
				</f:facet>

				<f:facet name="footer">
					<h:outputFormat value="#{fn:length(tipoContratoController.entities)} #{labels.registros_encontrados}" />
				</f:facet>
			</p:dataTable>

		</h:panelGrid>
	</ui:define>

	<ui:define name="editGrid">
		<h:panelGrid id="editGrid" width="100%" rendered="#{null != tipoContratoController.entity}">

			<p:fieldset legend="#{labels.informacoes}">
				<h:panelGrid columns="1">
					<p:outputLabel for="nome" value="#{labels.nome}" styleClass="label" />
					<p:inputText id="nome" style="width: 350px;" required="true" requiredMessage="#{labels.obrigatoriedade_nome}"
						value="#{tipoContratoController.entity.nome}" maxlength="50" />

					<p:outputLabel for="descricao" value="#{labels.descricao}" styleClass="label" />
					<p:inputTextarea id="descricao" style="width: 350px;" value="#{tipoContratoController.entity.descricao}" maxlength="400" autoResize="false"
						rows="8" />

					<h:panelGrid columns="3" style="width: 600px">
						<p:outputLabel for="modelo" value="#{labels.modelo}" styleClass="label" />
						<p:outputLabel for="aprovacaoPresidencia" value="#{labels.aprovacao_presidencia}" styleClass="label" />
						<p:outputLabel for="status" value="#{labels.status}" styleClass="label" />

						<p:selectOneMenu id="modelo" value="#{tipoContratoController.entity.modelo}" style="width:200px;" required="true"
							requiredMessage="#{labels.obrigatoriedade_modelo}">
							<f:selectItem itemLabel="#{labels.selecione}" itemValue="" />
							<f:selectItems value="#{domContratosController.modeloRequisicaoMap}" />
						</p:selectOneMenu>
						<p:selectOneMenu id="aprovacaoPresidencia" value="#{tipoContratoController.entity.aprovacaoPresidencia}" style="width:100px;">
							<f:selectItems value="#{domGeralController.booleanMap}" />
						</p:selectOneMenu>
						<p:selectOneMenu id="status" value="#{tipoContratoController.entity.status}" style="width:100px;" required="true"
							requiredMessage="#{labels.obrigatoriedade_status}">
							<f:selectItem itemLabel="#{labels.selecione}" itemValue="" />
							<f:selectItems value="#{domContratosController.statusTipoMap}" />
						</p:selectOneMenu>
					</h:panelGrid>

					<h:panelGrid rendered="#{tipoContratoController.editing}">
						<p:outputLabel value="#{labels.versao}" styleClass="label" />
						<p:outputLabel value="#{tipoContratoController.entity.versao}" styleClass="label" />
					</h:panelGrid>
				</h:panelGrid>
			</p:fieldset>

			<p:spacer />

			<p:fieldset legend="#{labels.minuta}">
				<h:panelGrid columns="1" id="minutaGrid">
					<h:panelGrid columns="2">
						<p:fileUpload fileUploadListener="#{tipoContratoController.uploadMinutaNovo}" mode="advanced" dragDropSupport="false"
							update=":editForm:messagesPanel :editForm:minutaGrid" skinSimple="true" allowTypes="/(\.|\/)(doc)$/"
							invalidFileMessage="#{labels.anexar_arquivo_doc} - #{labels.novo}" label="#{labels.atualizar} - #{labels.novo}" auto="true"
							style="min-width: 300px;" accept="application/msword" />
						<c:if test="#{null != tipoContratoController.conteudoMinutaNovo}">
							<span class="fa fa-fw fa-check" style="color: green !important; font-size: 20px;" />
						</c:if>
					</h:panelGrid>
					<h:panelGrid columns="2">
						<p:fileUpload fileUploadListener="#{tipoContratoController.uploadMinutaAditivo}" mode="advanced" dragDropSupport="false"
							update=":editForm:messagesPanel :editForm:minutaGrid" skinSimple="true" allowTypes="/(\.|\/)(doc)$/"
							invalidFileMessage="#{labels.anexar_arquivo_doc} - #{labels.aditivo}" label="#{labels.atualizar} - #{labels.aditivo}" auto="true"
							style="min-width: 300px;" accept="application/msword" />
						<c:if test="#{null != tipoContratoController.conteudoMinutaAditivo}">
							<span class="fa fa-fw fa-check" style="color: green !important; font-size: 20px;" />
						</c:if>
					</h:panelGrid>
					<h:panelGrid columns="2">
						<p:fileUpload fileUploadListener="#{tipoContratoController.uploadMinutaDistrato}" mode="advanced" dragDropSupport="false"
							update=":editForm:messagesPanel :editForm:minutaGrid" skinSimple="true" allowTypes="/(\.|\/)(doc)$/"
							invalidFileMessage="#{labels.anexar_arquivo_doc} - #{labels.distrato}" label="#{labels.atualizar} - #{labels.distrato}" auto="true"
							style="min-width: 300px;" accept="application/msword" />
						<c:if test="#{null != tipoContratoController.conteudoMinutaDistrato}">
							<span class="fa fa-fw fa-check" style="color: green !important; font-size: 20px;" />
						</c:if>
					</h:panelGrid>
				</h:panelGrid>
			</p:fieldset>

			<p:spacer />

			<p:fieldset legend="#{labels.versoes}">
				<p:dataTable widgetVar="dtbVersoes" id="dtbVersoes" var="entity" emptyMessage="#{labels.nenhuma_versao_encontrada}"
					value="#{tipoContratoController.versoes}">
					<p:column headerText="#{labels.nome}" style="text-align: center;">
						<h:outputText value="#{entity.nome}" />
					</p:column>

					<p:column headerText="#{labels.tipo_contrato}" style="text-align: center; width: 150px;">
						<h:outputText value="#{entity.deModelo}" />
					</p:column>

					<p:column headerText="#{labels.aprovacao_presidencia}" style="text-align: center; width: 200px;">
						<h:outputText value="#{entity.deAprovacaoPresidencia}" />
					</p:column>

					<p:column headerText="#{labels.versao}" style="text-align: center; width: 90px;">
						<h:outputText value="#{entity.id.versao}" />
					</p:column>

					<p:column headerText="#{labels.data}" style="text-align: center; width: 150px;">
						<h:outputText value="#{entity.data}">
							<f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss" timeZone="America/Sao_Paulo" />
						</h:outputText>
					</p:column>

					<p:column headerText="#{labels.novo}" sortBy="#{entity.nome}" style="text-align: center; width: 90px;">
						<p:commandButton icon="ui-icon-arrowthickstop-1-s" title="#{labels.download}" process="@this" ajax="false" immediate="true"
							onclick="liberaDownload(); PrimeFaces.monitorDownload(showStatus, hideStatus)" rendered="#{entity != null}">
							<p:fileDownload value="#{tipoContratoController.getArquivoMinuta(entity, 'N')}" />
						</p:commandButton>
					</p:column>

					<p:column headerText="#{labels.aditivo}" sortBy="#{entity.nome}" style="text-align: center; width: 90px;">
						<p:commandButton icon="ui-icon-arrowthickstop-1-s" title="#{labels.download}" process="@this" ajax="false" immediate="true"
							onclick="liberaDownload(); PrimeFaces.monitorDownload(showStatus, hideStatus)" rendered="#{entity != null}">
							<p:fileDownload value="#{tipoContratoController.getArquivoMinuta(entity, 'A')}" />
						</p:commandButton>
					</p:column>

					<p:column headerText="#{labels.distrato}" sortBy="#{entity.nome}" style="text-align: center; width: 90px;">
						<p:commandButton icon="ui-icon-arrowthickstop-1-s" title="#{labels.download}" process="@this" ajax="false" immediate="true"
							onclick="liberaDownload(); PrimeFaces.monitorDownload(showStatus, hideStatus)" rendered="#{entity != null}">
							<p:fileDownload value="#{tipoContratoController.getArquivoMinuta(entity, 'D')}" />
						</p:commandButton>
					</p:column>
				</p:dataTable>
			</p:fieldset>

			<p:spacer />
			<p:separator />
			<p:spacer />

			<p:scrollPanel id="messagesPanel" scrollMode="native" styleClass="messagesPanel">
				<p:messages />
			</p:scrollPanel>

			<p:toolbar>
				<p:toolbarGroup align="left">
					<p:commandButton id="submitButton" icon="fa fa-fw fa-save" value="#{labels.botao_gravar} " actionListener="#{tipoContratoController.save}"
						process="editGrid" update=":editForm :searchForm" />
					<p:commandButton icon="fa fa-fw fa-close" value="#{labels.botao_fechar}" actionListener="#{tipoContratoController.close}" process="@this"
						update=":searchForm :editForm" />
				</p:toolbarGroup>
			</p:toolbar>
		</h:panelGrid>
	</ui:define>
</ui:composition>
</html>